# Wikipage - Dummies Tensors Functions 

This jupyter notebook is in relation to the first part of the course on the deep learning provided by the speakers of the platform jovian.io. 

This first exercice will focus on how to use torch.tensor according the function present on the documentation https://pytorch.org/docs/stable/tensors.html#. The objective is to write a documentation about 5 functions.

### Subtitle Here
I selected five functions accross the differents sections in the pytorch package. 

- Mean
- Transpose
- Where
- Sum
- Numpy Array

In [16]:
# Import torch and other required modules
import torch


## mean

Compute the mean of all elements in the input tensor

Parameters: 
Input (tensor) :: the input tensor
Dim (int or tuple of python:ints) – the dimension or dimensions to reduce.
Keepdim (bool) – whether the output tensor has dim retained or not.
Out (Tensor, optional) – the output tensor.

In [46]:
# Generate values
x = torch.tensor([
     [1.5, 2.5, 3.5],
     [4.5, 5.5, 6.5]
   ])

Tensor contains values in 2 rows and 3 columns. 

In [47]:
x.shape

torch.Size([2, 3])

Compute the mean for all values

In [48]:
torch.mean(x)

tensor(4.)

We can also compute the mean for the dimension
If we specify the dimension to reduce, Pytorch will compute independently the mean for [1.5, 2.5, 3.5] and [4.5, 5.5, 6.5] dimensions in our example.

In [51]:
torch.mean(x, 1)

tensor([2.5000, 5.5000])

Last thing, we can specify if we want to keep the dimension when Pytorch compute the mean value

In [54]:
a = torch.randn(4, 4)
torch.mean(a, 1, True)

tensor([[-0.6970],
        [ 0.0291],
        [-0.6992],
        [ 0.1290]])

## torch.transpose()

With transposition, we can convert a row vector to a column vector and vice versa.
Parameters:
input (Tensor) – the input tensor.
dim0 (int) – the first dimension to be transposed
dim1 (int) – the second dimension to be transposed


Illustration of the transpose function: 
![Transpose](transpose.png)


In [59]:
x = torch.tensor([
     [1, 3],
     [2, 4]
   ])
print(torch.transpose(x, 0, 1))

tensor([[1, 3],
        [2, 4]])
tensor([[1, 2],
        [3, 4]])


## torch.where()

This function is used to specify conditions (like "where" in SQL) on X or Y elements.

Parameters: 
condition (BoolTensor) – When True (nonzero), yield x, otherwise yield y
x (Tensor) – values selected at indices where condition is True
y (Tensor) – values selected at indices where condition is False

In [92]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
y = torch.tensor([[4, 5, 6], [1, 2, 3]])

In [95]:
torch.where(x >= 4, x, y)

tensor([[4, 5, 6],
        [4, 5, 6]])

Explanation with illustration: 
![where-condition](where-condition.png)

## torch.sum()

Sum of all elements in the tensor

Parameters: 
input (Tensor) – the input tensor.
dim (int or tuple of python:ints) – the dimension or dimensions to reduce.
keepdim (bool) – whether the output tensor has dim retained or not.
dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.

In this example, we will sum all elements on the dimension 0. 
The follow example is equal to:
[[1, 3, 5] + [12, 14, 16]] = [13, 17, 21]

In [114]:
x = torch.tensor([[
     [1, 3, 5],
     [2, 4, 6]
   ], [
     [12, 14, 16],
     [11, 13, 15],
   ]])

torch.sum(x, (0))

tensor([[13, 17, 21],
        [13, 17, 21]])

One other example is to sum all elements according the dimension to reduce.  
The follow example is equal to: 
[[[1, 3, 5] + [2, 4, 6]], [[12, 14, 16]+[11, 13, 15]]] = [[[1+2, 3+4, 5+6]],[12+11, 14+13, 16+15]]] = [[[3,7,11]], [[23, 27, 31]]]

In [115]:
torch.sum(x, (1, 1), True)

tensor([[[ 3,  7, 11]],

        [[23, 27, 31]]])

## Function 5 -  numpy.ndarray
numpy() →
This function will create a torch from a numpy.ndarray. a numpy.ndarray is an array object that represents a multidimensional, homogeneous array of fixed-size items. 

Important things when you use this function: 

The returned tensor and ndarray share the same allocated memory. 
Every modifications to the tensor will be reflected in the ndarray and vice versa. 
The returned tensor is not resizable.

First of all, we declare an array with the numpy library:

In [61]:
import numpy

data = numpy.array([1, 2, 3])
print(data)

[1 2 3]


Then, we can convert this numpy array in tensor 

In [64]:
tensor = torch.from_numpy(data)
print(tensor)

tensor([1, 2, 3])


## Reference Links
A curated list of articles about deep-learning concepts and Pytorch
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Towards Data Science - Medium - Brendan Fortuner
https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c
* Scalars, Vectors Matrices and Tensors - Hadrien J - Blog
https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/
* Toward Data Science - Medium - Boyan Barakov
https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be
* WTF IS TENSOR - KDNUGGETS - Matthew Mayo https://www.kdnuggets.com/2018/05/wtf-tensor.html

## Helpers - Installation

Some help to resolve issues with the jupyter notebook install: 
    
Environment conflicts - ResolvePackageNotFound: it fails because the YAML includes platform-specific build constraints and because the file is transfered across platforms.

In order to solve that problem, before the installation run the command:     

In [ ]:
conda env export --no-builds > environment.yml

Then

In [ ]:
jovian install

More informations:
https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
